unalias -a

source ~/.config/terminal/common.sh

source ~/.config/bash/colors.sh
source ~/.config/bash/history.sh
source ~/.config/bash/prompt.sh

source ~/.config/bash/completion.sh

source ~/.config/terminal/extras.sh
