version: '3.2'

services:
  devstat_server:
    image: thekevjames/devstat-server:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 20s
      update_config:
        parallelism: 1
        monitor: 20s
    secrets:
      - github_token

  devstat_web:
    image: thekevjames/devstat-web:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 20s
      update_config:
        parallelism: 1
        monitor: 20s

secrets:
  github_token:
    external: true
