version: '3.2'

services:
  devstat_server:
    build: server/.
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8081:80"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/run/secrets/google_service_creds

  devstat_web:
    build: web/.
    ports:
      - "8080:80"
