class { '::sublime':
  home    => '/root',
  plugins => ["ANSIescape",
              "Better CoffeeScript",
              "BracketHighlighter",
              "BufferScroll",
              "Case Conversion",
              "Dockerfile Syntax Highlighting",
              "Fold Python Docstrings",
              "Increment Selection",
              "JSON Reindent",
              "Markdown Preview",
              "Origami",
              "Package Control",
              "Puppet",
              "Reform",
              "RuboCop",
              "Sass",
              "Sort Lines (Numerically)",
              "SublimeLinter",
              "SublimeLinter-annotations",
              "SublimeLinter-chktex",
              "SublimeLinter-cppcheck",
              "SublimeLinter-html-tidy",
              "SublimeLinter-phpcs",
              "SublimeLinter-pylint",
              "SublimeLinter-ruby",
              "SublimeLinter-shellcheck",
              "Sync View Scroll"],
}
